In [272]:
import pandas as pd 
df1 = pd.read_csv("./data/1000000-bandcamp-sales.csv")

In [171]:
df1.head()

,Unnamed: 0,_id,art_url,item_type,utc_date,country_code,track_album_slug_text,country,slug_type,amount_paid_fmt,...,amount_paid,releases,artist_name,currency,album_title,amount_paid_usd,package_image_id,amount_over_fmt,item_slug,addl_count
0,0,1599688803.5175&//girlbanddublin.bandcamp.com/...,https://f4.bcbits.com/img/a0206405257_7.jpg,a,1.599689e+09,gb,NaN,United Kingdom,a,$9.99,...,9.99,NaN,Girl Band,USD,NaN,9.99,NaN,NaN,NaN,NaN
1,1,1599688805.27838&//maharettarecords.bandcamp.c...,https://f4.bcbits.com/img/a2984241552_7.jpg,a,1.599689e+09,fi,NaN,Finland,a,£1,...,1.00,NaN,Jirah,GBP,NaN,1.30,NaN,NaN,NaN,NaN
2,2,1599688805.90646&//maharettarecords.bandcamp.c...,https://f4.bcbits.com/img/a3320494770_7.jpg,a,1.599689e+09,fi,NaN,Finland,a,£3,...,3.00,NaN,D-Ther,GBP,NaN,3.90,NaN,NaN,NaN,NaN
3,3,1599688806.94234&//alicesitski.bandcamp.com/al...,https://f4.bcbits.com/img/0020476345_37.jpg,p,1.599689e+09,gb,NaN,United Kingdom,a,€10.50,...,10.50,NaN,WHITE NOISE TV,EUR,WHITE NOISE TV,12.39,20476345.0,NaN,NaN,NaN
4,4,1599688809.07942&//linguaignota.bandcamp.com/t...,https://f4.bcbits.com/img/a3428873396_7.jpg,t,1.599689e+09,us,NaN,United States,t,$1,...,1.00,NaN,LINGUA IGNOTA,USD,NaN,1.00,NaN,NaN,NaN,NaN

In [1]:
import pandas as pd 
df = pd.read_csv("./data/location.csv", encoding="ISO-8859-1",sep='|')

In [12]:
df2 = pd.unique(df[['lon', 'lat']].values.ravel())
print(df2)

[18.0685808 59.3293235 -3.010113  ... 51.789534  -0.2784385 39.6798633]

In [7]:
df

,locate_id,City,Country,Region,State,lon,lat
0,1,Stockholm,Sweden,North,Stockholm,18.068581,59.329324
1,2,Southport,United Kingdom,North,England,-3.010113,53.645708
2,3,Valence,France,Central,Auvergne-Rhône-Alpes,4.892360,44.933393
3,4,Birmingham,United Kingdom,North,England,-1.890401,52.486243
4,5,Echirolles,France,Central,Auvergne-Rhône-Alpes,5.718034,45.142151
...,...,...,...,...,...,...,...
4112,4113,Bielefeld,Germany,Central,North Rhine-Westphalia,8.532471,52.030228
4113,4114,Maidenhead,United Kingdom,North,England,-0.721900,51.522414
4114,4115,Worcester,United Kingdom,North,England,-2.221575,52.193636
4115,4116,Hamburg,Germany,Central,Hamburg,9.993682,53.551085
4116,4117,Eindhoven,Netherlands,Central,North Brabant,5.469722,51.441642

In [32]:
import wget
URL = "https://www.dropbox.com/s/wd38q80el16i19q/1000000-bandcamp-sales.zip?dl=1"
response = wget.download(URL, out='data/1000000-bandcamp-sales.zip')

In [ ]:
import zipfile
import pandas as pd

zip_file = "data/1000000-bandcamp-sales.zip"  # Replace with the path to your zip file
csv_file = "data/1000000-bandcamp.csv"  # Replace with the name of the CSV file within the zip

# Extract the CSV file from the zip archive
with zipfile.ZipFile(zip_file, "r") as zf:
    # Assuming the CSV file is in the root directory of the zip file
    csv_data = zf.read(csv_file)

# Read the CSV data into a pandas DataFrame
df = pd.read_csv(pd.compat.StringIO(csv_data.decode('utf-8')))

# Now you can work with the DataFrame
print(df.head())

In [37]:
df=pd.read_csv("https://www.dropbox.com/s/wd38q80el16i19q/1000000-bandcamp-sales.zip?dl=1",encoding="ISO-8859-1")

ParserError: Error tokenizing data. C error: Expected 2 fields in line 3, saw 3

In [51]:
import configparser
import wget
config = configparser.ConfigParser()
config.read('./config.ini')
config["PREFECT"]['GcsBucket_block']

'zoom-gcs'

In [35]:
df

,Unnamed: 0,_id,art_url,item_type,utc_date,country_code,track_album_slug_text,country,slug_type,amount_paid_fmt,...,amount_paid,releases,artist_name,currency,album_title,amount_paid_usd,package_image_id,amount_over_fmt,item_slug,addl_count
0,0,1599688803.5175&//girlbanddublin.bandcamp.com/...,https://f4.bcbits.com/img/a0206405257_7.jpg,a,1.599689e+09,gb,NaN,United Kingdom,a,$9.99,...,9.99,NaN,Girl Band,USD,NaN,9.99,NaN,NaN,NaN,NaN
1,1,1599688805.27838&//maharettarecords.bandcamp.c...,https://f4.bcbits.com/img/a2984241552_7.jpg,a,1.599689e+09,fi,NaN,Finland,a,£1,...,1.00,NaN,Jirah,GBP,NaN,1.30,NaN,NaN,NaN,NaN
2,2,1599688805.90646&//maharettarecords.bandcamp.c...,https://f4.bcbits.com/img/a3320494770_7.jpg,a,1.599689e+09,fi,NaN,Finland,a,£3,...,3.00,NaN,D-Ther,GBP,NaN,3.90,NaN,NaN,NaN,NaN
3,3,1599688806.94234&//alicesitski.bandcamp.com/al...,https://f4.bcbits.com/img/0020476345_37.jpg,p,1.599689e+09,gb,NaN,United Kingdom,a,€10.50,...,10.50,NaN,WHITE NOISE TV,EUR,WHITE NOISE TV,12.39,20476345.0,NaN,NaN,NaN
4,4,1599688809.07942&//linguaignota.bandcamp.com/t...,https://f4.bcbits.com/img/a3428873396_7.jpg,t,1.599689e+09,us,NaN,United States,t,$1,...,1.00,NaN,LINGUA IGNOTA,USD,NaN,1.00,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,1601647409.59517&//eternalchampion.bandcamp.co...,https://f4.bcbits.com/img/0021839465_37.jpg,p,1.601647e+09,ca,NaN,Canada,a,$20,...,20.00,NaN,Eternal Champion,USD,RAVENING IRON,20.00,21839465.0,NaN,NaN,NaN
999996,999996,1601647409.61911&//goodmusic2020.bandcamp.com/...,https://f4.bcbits.com/img/a3708391191_7.jpg,a,1.601647e+09,us,NaN,United States,a,$20.20,...,20.20,NaN,Various Artists Working to Avert the Collapse ...,USD,NaN,20.20,NaN,NaN,NaN,NaN
999997,999997,1601647409.63413&//geometriclullaby.bandcamp.c...,https://f4.bcbits.com/img/a0358085735_7.jpg,a,1.601647e+09,au,NaN,Australia,a,$1,...,1.00,NaN,w i n t e r q u i l t,USD,NaN,1.00,NaN,NaN,NaN,NaN
999998,999998,1601647409.77243&//bewitcher.bandcamp.com/merc...,https://f4.bcbits.com/img/0019759485_37.jpg,p,1.601647e+09,us,NaN,United States,p,$6,...,6.00,NaN,Bewitcher,USD,NaN,6.00,19759485.0,NaN,NaN,NaN
999999,999999,1601647410.21167&//jonsi.bandcamp.com/album/sh...,https://f4.bcbits.com/img/0020487835_37.jpg,p,1.601647e+09,gb,NaN,United Kingdom,a,£30,...,30.00,NaN,Jónsi,GBP,Shiver,38.59,20487835.0,NaN,NaN,NaN